const getters={
    nodeId: state => state.graph.nodeId,
    labelList: state => state.graph.labelList,
    relationId: state => state.graph.relationId,
    showGraphEdges: state => state.graph.showGraphEdges,
    showGraphNodes: state => state.graph.showGraphNodes,
    graphInfo: state => state.graph.graphInfo,
    picId: state=>state.graph.picId,
    customizeElement: state => state.graph.customizeElement,
    nodes: state=>state.graph.nodes,
    links: state=>state.graph.links,
    showGraphInfo: state => state.graph.showGraphInfo,
    relationTypeSet: state=>state.graph.relationTypeSet,
    currentPicId: state=>state.graph.currentPicId,
    currentGraph: state=>state.graph.currentGraph,
    currentGraphId: state=>state.graph.currentGraphId,
    graphIds: state=>state.graph.graphIds,
    forceGraph: state=>state.graph.forceGraph,
    typesettingGraph: state=>state.graph.typesettingGraph,
    showDownloadImgModal: state=>state.graph.showDownloadImgModal,
    showDownloadFileModal: state=>state.graph.showDownloadFileModal,
    currentSetLayout: state=>state.graph.currentSetLayout,
    forceGraphRatio: state=>state.graph.forceGraphRatio,
    typesettingGraphRatio: state=>state.graph.typesettingGraphRatio,
    forceLayout: state=>state.graph.forceLayout,
    layoutType: state=>state.graph.layoutType,
    edgesTypeCntMap: state=>state.graph.edgesTypeCntMap,
    nodesTypeCntMap: state=>state.graph.nodesTypeCntMap,
    searchNodes: state=>state.graph.searchNodes,
    searchEdges: state=>state.graph.searchEdges,
    nodesByTypeMap: state=>state.graph.nodesByTypeMap,
    nodesTypes: state=>state.graph.nodesTypes,
    isNew: state=>state.graph.isNew,
    currentGraphData: state=>state.graph.currentGraphData,
    currentShowGraphData: state=>state.graph.currentShowGraphData,
    forceShowEdgeLabel: state=>state.graph.forceShowEdgeLabel,
    typesettingEdgeShowLabel: state=>state.graph.typesettingEdgeShowLabel,
    currentCombos: state=>state.graph.currentCombos,
    currentShowCombos: state=>state.graph.currentShowCombos,
    currentItem: state=>state.graph.currentItem,
    // showEditNodeModal: state=>state.graph.showEditNodeModal,
    // showEditEdgeModal: state=>state.graph.showEditEdgeModal,
    boardTypes: state=>state.graph.boardTypes,
    currentShowBoard: state=>state.graph.currentShowBoard,
    checkList:state=>state.graph.checkList,

    colorList: state=>state.util.colorList,

    userId: state=>state.user.userId,
    userInfo: state=>state.user.userInfo,
    picsInfo: state=>state.user.picsInfo,
    userHistory: state=>state.user.userHistory,
    // addEntityVisible: state=>state.util.addEntityVisible,
    // addRelationVisible: state=>state.util.addRelationVisible,
    // pieModalVisible: state=>state.util.pieModalVisible,

};
export default getters
